export const actionsType = {
    SEARCH_INPUT : 'SEARCH_INPUT',
    GET_BY_ID : 'GET_BY_ID_CLAIM',
    GET_ALL_CLASS: 'GET_ALL_CLASS',
    SET_USER_DATA: 'SET_USER_DATA',
    MODIFICAR_CLASES_POR_COMPRAR: 'MODIFICAR_CLASES_POR_COMPRAR',
    MODIFICAR_USUARIO_LOGUEADO: 'MODIFICAR_USUARIO_LOGUEADO',
    MODIFICAR_CANTIDAD_CLASES_POR_COMPRAR: 'MODIFICAR_CANTIDAD_CLASES_POR_COMPRAR'
}

