export const actionsType = {
    SEARCH_INPUT : 'SEARCH_INPUT',
    GET_BY_ID : 'GET_BY_ID_CLAIM',
    GET_ALL_CLAIMS: 'GET_ALL_CLAIMS',
    SET_USER_DATA: 'SET_USER_DATA',
    MODIFICAR_CLASES_POR_COMPRAR: 'MODIFICAR_CLASES_POR_COMPRAR',
    CALENDAR_TO_ADDCLASS: "CALENDAR_TO_ADDCLASS",
    SET_FETCH_CALENDAR: "SET_FETCH_CALENDAR"
}

